-- -----------------------------------------------------
-- Table `pdapp_datasetfile`- Stores information about files belonging to datasets
-- ----------------------------------------------------- 
create table pdapp_datasetfile (
  id bigint generated by default as identity primary key, 
  name varchar(200) not null, 
  description varchar(2000) not null, 
  file_csv varchar(200) not null, 
  provider varchar(200) not null, 
  date_creation timestamp with time zone not null, 
  confirmed boolean not null, 
  created_by_id integer not null constraint pdapp_datasetfile_created_by_id_89a2d270_fk_auth_user_id references auth_user deferrable initially deferred, 
  dataset_id bigint not null constraint pdapp_datasetfile_dataset_id_7773aff1_fk_pdapp_dataset_id references pdapp_dataset deferrable initially deferred
);

alter table 
  pdapp_datasetfile owner to root;
